'âœ chore: profile':
  - 'data/**'

tests:
  - 'tests/**'

storybook:
  - 'stories/**'

dependencies:
  - 'package.*'

'CI/CD':
  - '.github/**'

'ğŸ“– docs':
  - 'pages/docs/**'

'models':
  - 'models/**'
