name: Format
on:
  workflow_dispatch:
  #Run every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "main-branch"

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Files
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Prettier
        run: npx prettier --write data/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: format-files
        with:
          commit_message: "style: format files"
          skip_checkout: true
          branch: "formatting-${{ github.sha }}"
          create_branch: true

      # create PR using GitHub CLI if files were formatted
      - name: create PR with formatted files
        if: steps.format-files.outputs.changes_detected == 'true'
        id: create-pr
        run: git checkout formatting-${{ github.sha }} && gh pr create --base main --head formatting-${{ github.sha }} --title 'Merge formatting into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # merge PR using GitHub CLI
      - name: merge PR with adjusted formatting
        if: steps.format-files.outputs.changes_detected == 'true'
        id: merge-pr
        run: gh pr merge --admin --merge --subject 'Merge formatting' --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
